# Site settings
title: Mariel's Enumerated Musings
header-img: img/home-bg.png
email: marielbeth@gmail.com
copyright_name: marielfrank
description: > # this means to ignore newlines until "baseurl:"
  Adventures in Programming
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: marielsmusings
github_username:  marielfrank
learn_profile: marielfrank
email_username: marielbeth@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
